package com.example.soto.memoramaprueba.schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USERS".
 */
public class Users {

    private Long id;
    /** Not-null value. */
    private String userName;
    /** Not-null value. */
    private String nickName;
    /** Not-null value. */
    private String password;
    /** Not-null value. */
    private String imageURL;
    private long bestScore;

    public Users() {
    }

    public Users(Long id) {
        this.id = id;
    }

    public Users(Long id, String userName, String nickName, String password, String imageURL, long bestScore) {
        this.id = id;
        this.userName = userName;
        this.nickName = nickName;
        this.password = password;
        this.imageURL = imageURL;
        this.bestScore = bestScore;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getUserName() {
        return userName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /** Not-null value. */
    public String getNickName() {
        return nickName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }

    /** Not-null value. */
    public String getPassword() {
        return password;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPassword(String password) {
        this.password = password;
    }

    /** Not-null value. */
    public String getImageURL() {
        return imageURL;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setImageURL(String imageURL) {
        this.imageURL = imageURL;
    }

    public long getBestScore() {
        return bestScore;
    }

    public void setBestScore(long bestScore) {
        this.bestScore = bestScore;
    }

    @Override
    public String toString() {
        return "Users{" +
                "id=" + id +
                ", userName='" + userName + '\'' +
                ", nickName='" + nickName + '\'' +
                ", password='" + password + '\'' +
                ", imageURL='" + imageURL + '\'' +
                ", bestScore=" + bestScore +
                '}';
    }
}
